#!/bin/bash
### BEGIN INIT INFO
# Provides:     kestrel
# Required-Start:   $syslog
# Required-Stop:    $syslog
# Should-Start:     $local_fs
# Should-Stop:      $local_fs
# Default-Start:    2 3 4 5
# Default-Stop:     0 1 6
# Short-Description:    kestrel - message queue
# Description:      kestrel - message queue
### END INIT INFO

PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:$PATH
AS_USER="deploy"

APP_NAME="kestrel"
APP_HOME="/var/backends/kestrel"
PID_DIR="/var/run/${APP_NAME}"
LOG_DIR="/var/log/${APP_NAME}"

JAVA=`which java`
JVM_OPS="-server -Xmx386m -Xms386m -XX:+UseConcMarkSweepGC -XX:+UseParNewGC"
JAVA_CONFIG="$JVM_OPS -Dstage=production -jar kestrel-1.3.0.jar"

daemon_args="--name $APP_NAME --user $AS_USER --pidfile $PID_DIR/pid --stdout=$LOG_DIR/output.log --stderr=$LOG_DIR/error.log --chdir $APP_HOME"

if [ "x$JAVA" == "x" ]; then
    echo "java not found!"
    exit 1
fi

function running() {
    daemon $daemon_args --running
}

function start_server() {

    mkdir -p $PID_DIR
    mkdir -p $LOG_DIR
    chown -R $AS_USER $PID_DIR
    chown -R $AS_USER $LOG_DIR

    if running; then
        echo "$APP_NAME already running."
        exit 0
    fi
    echo "Starting $APP_NAME"
    daemon $daemon_args -- $JAVA $JAVA_CONFIG
}

case "$1" in
    start)
        start_server;
        ;;
    stop)
        if ! running; then
            echo "$APP_NAME not running."
            exit 0
        fi
        echo "Stopping $APP_NAME"
        daemon $daemon_args --stop
        ;;
    status)
        if running; then
            echo "$APP_NAME running"
        else
            echo "$APP_NAME not running"
        fi
        ;;
    restart|force-reload)
        while running
        do
            $0 stop
            sleep 1;
        done
        $0 start
        ;;
    *)
        echo "Usage: /etc/init.d/$APP_NAME {start|status|stop|restart|force-reload}" >&2
        exit 1
        ;;
esac

exit 0
